# Generated by Django 4.1.5 on 2023-02-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flights.airline'),
            preserve_default=False,
        ),
    ]
